### ISSUE TITLE
App crashes on initialisation when I release appbundle

### ISSUE THREAD

**Issue by savjolovs** [dooboolab/flutter_inapp_purchase#93]
### Version of flutter_inapp_purchase 
0.9.2

### Platforms you faced the error (IOS or Android or both?)
Android

I initialise billing as in the example and if I run the app on my device/emulator everything works fine. As soon as I release the app using appbundle I get crash on initialisation. If I build and release apk everything works fine.
Is anyone facing the same issue?

**Comment by hyochan** [comment]
I've posted `deprecation` note today since I think it is quite useless when official plugin is released.

**Comment by ollydixon** [comment]
@hyochan I wish you'd kept this project going it's much better than the offical one. Also the official one has so many bugs :-/ (Cannot continue translation for example)

**Comment by stemuk** [comment]
@hyochan I can only agree with @ollydixon , the 'official' `in_app_purchase` package is more than useless. My main gripe is the sheer amount of bugs and undocumented behavior and most notably the fact that almost every action (initialization etc.) that previously in your package took only one step now takes several to make it work.

**Comment by ollydixon** [comment]
@stemuk and that the official one doesn't even return proper promises or refresh consumerables on iOS (Current major bug). It has a crappy Stream.listen fail..

**Comment by hyochan** [comment]
@stemuk @ollydixon Thanks for the feed back. Alright then I'll try to continue working on it and release you one this weekend.

**Comment by ollydixon** [comment]
@hyochan thank you.

**Comment by hyochan** [comment]
@ollydixon @stemuk Sorry that I've had a hard time maintaining other projects so I wasn't able to take my time here. I am back now and I actually want to get the feedback again not to waste my time.
Is the official library still bad? Do you still think this should be maintained?

**Comment by ollydixon** [comment]
@hyochan they are still bad but managable. They have many bugs and hard ways to implement things that should be easy.

**Comment by hyochan** [comment]
Please give any other comments on this so I can get motivated to work on this.

**Comment by ziggycrane** [comment]
Official plugin is unusable man, we need you!

**Comment by alekxlight** [comment]
Totally agree with ziggycrane!  My app is ready to be released except for in-app purchases and the official version will not work.  Thanks in advance!

**Comment by hyochan** [comment]
Hi everyone~ I am planning for a new release starting from `2.0.0`. Currently work in progress in #94.

**Comment by hyochan** [comment]
Looks like I've just released flutter_inapp_purcase@2.0.0 which is a `sunrise` 🌅 ! Some features are not tested yet but I've tested new `purchase flow`.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.

**Comment by sallymariehollywood** [comment]
Hi - I'm planning to build inApp subscription purchasing - just a few questions :- 

a) is this plugin still being maintained
b) is it recommended to use this plugin or the official one ?
c) does this support latest iOS 13 release ?

Lastly what is the recommended way using this plugin to take (say) a 'free/lite' app and expose all FULL features of an app once a subscription has been purchased - I couldnt see any examples of the plugin that showed a technique for this.

Thank you

**Comment by atessift** [comment]
Looks like the official plugin still does not support basic features like upgrading/downgrading between subscriptions. Please keep working on this! (and maybe we should convince the Google Flutter team to simply adopt this plugin instead of working on their duplicate)

**Comment by va0000ll** [comment]
Hope you continue working on this, great work

**Comment by erperejildo** [comment]
> Hi - I'm planning to build inApp subscription purchasing - just a few questions :-
> 
> a) is this plugin still being maintained
> b) is it recommended to use this plugin or the official one ?
> c) does this support latest iOS 13 release ?
> 
> Lastly what is the recommended way using this plugin to take (say) a 'free/lite' app and expose all FULL features of an app once a subscription has been purchased - I couldnt see any examples of the plugin that showed a technique for this.
> 
> Thank you

I also would like to know

**Comment by schankam** [comment]
Just a word to tell you to keep up the amazing work you've been doing, you're saving a lots of us at the moment since the official plugin is unusable on iOS.

**Comment by averstuyf** [comment]
Can confirm. Our startup lost an incredible amount of time trying to make the official plugin work. Well, it doesn't, at least for iOS. This does not bode well for Flutter as a platform when the Google developers spend time on porting stuff to the web before make their libraries official code work. 

Please, keep up the good work. Until the rest of us are well versed enough in this platform, it is up to you to keep it alive. Thank you.

**Comment by ollydixon** [comment]
@averstuyf @schankam I would also like to add to this, usually don't hijack issue forms like this but I had to. We tried to implement the official plugin for more than 9 apps now and we've always had to revert back to this plugin. Keep up the good work, it works flawlessly for us on iOS and Android; what next Web? 😂🥳 (Maybe using a Stripe plugin?)

**Comment by yangfanyu** [comment]
There are a lot of problems with the official plugin. This plugin is excellent！

**Comment by kslr** [comment]
Even today, you cannot perform downgrades or upgrades on Android, nor can you handle promo codes through the in_app_purchase. It's incredible.

**Comment by giantss** [comment]
Is this plugin no longer maintained?

Many questions have been reported for a long time but no one has responded.
